name       : djvulibre
version    : 3.5.28
release    : 8
source     :
    - https://download.sourceforge.net/project/djvu/DjVuLibre/3.5.28/djvulibre-3.5.28.tar.gz : fcd009ea7654fde5a83600eb80757bd3a76998e47d13c66b54c8db849f8f2edc
homepage   : http://djvu.sourceforge.net/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A web-centric format and software platform for distributing documents and images
description: |
    DjVu (pronounced "déjà vu") a set of compression technologies, a file format, and a software platform for the delivery over the Web of digital documents, scanned documents, and high resolution images.
builddeps  :
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(librsvg-2.0)
setup      : |
    %apply_patches
    %configure
build      : |
    %make
install    : |
    %make_install
    # Remove broken mime metadata, breaks evince support for djvu
    rm -rf $installdir/usr/share/mime
