name       : djvulibre
version    : 3.5.27
release    : 3
source     :
    - http://liquidtelecom.dl.sourceforge.net/project/djvu/DjVuLibre/3.5.27/djvulibre-3.5.27.tar.gz : e69668252565603875fb88500cde02bf93d12d48a3884e472696c896e81f505f
license    : GPL-2.0+
component  : desktop.library
summary    : DjVu
description: |
    DjVu (pronounced "déjà vu") a set of compression technologies, a file format, and a software platform for the delivery over the Web of digital documents, scanned documents, and high resolution images.
builddeps  :
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(librsvg-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Remove broken mime metadata, breaks evince support for djvu
    rm -rf $installdir/usr/share/mime
